__title__ = "openva_pipeline"
__description__ = "Automates the processing of verbal autopsy data."
__url__ = "https://github.com/verbal-autopsy-software/openva_pipeline"
__version__ = "0.9.5"
__author__ = "Jason Thomas, Samuel J. Clark, & Martin W. Bratschi"
__author_email__ = "jarthomas@gmail.com"
__license__ = "GPLv3"
